name: Deployment pipeline

on:
  push:
    branches:
      - react-version

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install backend dependencies
        run: cd ./backend && npm install
      - name: Install frontend dependencies
        run: cd ../frontend && npm install
      - name: Check frontend style
        run: npm run lint